services:
  web:
      build: .
      command: gunicorn --workers=3 --bind 0.0.0.0:8000 django_aws.wsgi:application
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - postgres
      environment:
        DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
        GITHUB_SECRET_KEY: ${GITHUB_SECRET_KEY}
        AFRICAS_TALKING_USERNAME: ${AFRICAS_TALKING_USERNAME}
        AFRICAS_TALKING_API_KEY: ${AFRICAS_TALKING_API_KEY}
  postgres:
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"