version: "3.8"

services:
  web:
      build: .
      command: gunicorn --workers=3 --bind 0.0.0.0:8000 django_aws.wsgi:application
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - postgres
      environment:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/customer_orders_db
  postgres:
    image: "postgres:14"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "customer_orders_db"